### ISSUE TITLE
Concurrency issue with uploads causing uploads to run twice.

### ISSUE THREAD

**Issue by bearjaws** [johnjones4/BackupTool#5]
I am not 100% sure where this is coming from, but with logging enabled you will see that all files get logged twice.

Will Backup "/Users/michael/Documents/backups/test.large"
Will Backup "/Users/michael/Documents/backups/test.large"

At first I thought this was a logging issue, but I created test.large as a 100mb file and when I monitor my upload bandwidth I see that the file is indeed uploaded twice (200mb of upload used)

I believe this can be prevented by ensuring sqlite is updated with the status of the upload such that `getNextFileForBackup` does not retrieve rows that are currently being uploaded.

**Comment by johnjones4** [comment]
I saw this crop up once before but I've been unable to replicate. Right now it updates the 'backedup' column in sqlite in the `getNextFileForBackup` so that it doesn't get double-queue. (However, on error, it resets that column to 0 so that may be the cause?)
